### ISSUE TITLE
TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by Jean-Carlo-Oliveira-Santos** [itsayushisaxena/Get_Old_Tweets-Python#3]
Every time I run the code, this error appears "TypeError: Multiple inheritance with NamedTuple is not supported". I don't know what I did wrong!
Code with error:

c:\users\jean\appdata\local\programs\python\python39\lib\typing.py in _namedtuple_mro_entries(bases)
   1818 def _namedtuple_mro_entries(bases):
   1819     if len(bases) > 1:
-> 1820         raise TypeError("Multiple inheritance with NamedTuple is not supported")
   1821     assert bases[0] is NamedTuple
   1822     return (_NamedTuple,)

TypeError: Multiple inheritance with NamedTuple is not supported

**Comment by itsayushisaxena** [comment]
Hey!
Have you done any changes to the code? If yes, kindly paste the modified code here so that I'll be able to figure out where the error arises.

**Comment by Jean-Carlo-Oliveira-Santos** [comment]
@AyushiiSaxena  
As I realized it was a problem in the code of the file "typing" in a python lib.
I edited it to skip the condition that gave the error and managed to successfully extract the tweets.
Thank you very much for your attention!

**Comment by itsayushisaxena** [comment]
@Jean-Carlo-Oliveira-Santos 
That's great. Thanks for your appreciation!
